repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.35.0
    hooks:
      - id: eslint
        name: eslint
        entry: eslint
        language: node
        files: ^frontend/.*\.(js|jsx|ts|tsx)$

  # - repo: local
  #   hooks:
  #     - id: typescript-typecheck
  #       name: typescript-typecheck
  #       entry: npx tsc --noEmit
  #       language: node
  #       files: ^frontend/.*\.(ts|tsx)$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        files: ^backend/.*\.py$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
      - id: ruff-format
