name: 'Setup Poetry Environment'
description: 'Sets up Python, caches virtualenv and pip wheels, installs Poetry with plugin, and optionally installs dependencies.'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.12'
  install-deps:
    description: 'Set to true to run poetry install (with all groups).'
    required: false
    default: 'true'
  poetry-version:
    description: 'Poetry version spec (e.g., 1.8.*)'
    required: false
    default: '1.8.*'
  install-export-plugin:
    description: 'Install poetry-plugin-export (requires Poetry >=1.7, plugin itself >=1.8, >=1.9 needs Poetry >=2.0)'
    required: false
    default: 'true'
  cache-key-suffix:
    description: 'Extra suffix to differentiate caches (e.g., job name)'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache pip wheels
      id: pip-cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          pip-${{ runner.os }}-py${{ inputs.python-version }}-

    - name: Cache virtualenv
      id: venv-cache
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-py${{ inputs.python-version }}-${{ hashFiles('poetry.lock') }}${{ inputs.cache-key-suffix }}
        restore-keys: |
          venv-${{ runner.os }}-py${{ inputs.python-version }}-

    - name: Install Poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install "poetry==${{ inputs.poetry-version }}"
        if [ "${{ inputs.install-export-plugin }}" = "true" ]; then
          # Try a version of the plugin compatible with Poetry <2 first
          set -e
          if poetry self add 'poetry-plugin-export<1.9.0' 2>/dev/null; then
            echo "Installed export plugin <1.9.0 for Poetry <2 compatibility";
          else
            echo "Falling back; attempting latest poetry-plugin-export (may require Poetry >=2).";
            poetry self add poetry-plugin-export || echo "Warning: export plugin install failed; continuing without plugin";
          fi
        else
          echo "Skipping poetry-plugin-export installation as requested.";
        fi
        poetry --version
      env:
        POETRY_VIRTUALENVS_IN_PROJECT: "true"
        POETRY_VIRTUALENVS_CREATE: "true"

    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        poetry install --all-groups
      env:
        POETRY_VIRTUALENVS_IN_PROJECT: "true"
        POETRY_VIRTUALENVS_CREATE: "true"
