name: coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: pip install poetry
      - name: Install deps
        run: |
          poetry install --with dev
      - name: Run coverage
        run: |
          poetry run pytest --cov=src --cov-report=term --cov-report=xml --cov-report=html
      - name: Enforce coverage threshold
        run: |
          # Adjust threshold as needed
          poetry run coverage report --fail-under=85
      - name: Generate coverage badge
        run: |
          poetry run coverage-badge -o coverage.svg -f
      - name: Commit coverage badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          mkdir -p badges
          mv coverage.svg badges/coverage.svg
          git add badges/coverage.svg
          if git diff --cached --quiet; then
            echo "No coverage badge changes to commit"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Extract percentage for richer commit message if coverage.xml exists
          if [ -f coverage.xml ]; then
            percent=$(grep -o 'line-rate="[0-9.]*"' coverage.xml | head -1 | cut -d '"' -f2)
            pct=$(python -c "print(int(round(float('${percent}')*100)))") || pct="?"
            git commit -m "chore: update coverage badge to ${pct}%" || echo "Nothing to commit"
          else
            git commit -m "chore: update coverage badge" || echo "Nothing to commit"
          fi
          git push
      - name: Upload coverage badge artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: badges/coverage.svg
