name: Test Coverage Badge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '2.*'

      - name: Install dependencies
        run: |
          poetry install --all-groups

      - name: Run tests with coverage
        run: |
          poetry run coverage run -m pytest -q
          poetry run coverage xml
          poetry run coverage report

      - name: Generate coverage percentage
        id: coverage
        run: |
          percent=$(grep -o 'line-rate="[0-9.]*"' coverage.xml | head -1 | cut -d '"' -f2)
          # Convert to percentage (rate * 100 rounded)
          pct=$(python -c "print(int(round(float('$percent')*100)))")
          echo "pct=$pct" >> $GITHUB_OUTPUT

      - name: Create badge SVG
        run: |
          pct=${{ steps.coverage.outputs.pct }}
          color=brightgreen
          if [ "$pct" -lt 90 ]; then color=yellowgreen; fi
          if [ "$pct" -lt 80 ]; then color=yellow; fi
          if [ "$pct" -lt 70 ]; then color=orange; fi
          if [ "$pct" -lt 60 ]; then color=red; fi
          cat > badges/coverage.svg <<EOF
          <svg xmlns="http://www.w3.org/2000/svg" width="120" height="20" role="img" aria-label="coverage:${pct}%"><title>coverage:${pct}%</title><linearGradient id="s" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="r"><rect width="120" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#r)"><rect width="63" height="20" fill="#555"/><rect x="63" width="57" height="20" fill="#${color}"/><rect width="120" height="20" fill="url(#s)"/></g><g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110"><text aria-hidden="true" x="325" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="530">coverage</text><text x="325" y="140" transform="scale(.1)" fill="#fff" textLength="530">coverage</text><text aria-hidden="true" x="905" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="370">${pct}%</text><text x="905" y="140" transform="scale(.1)" fill="#fff" textLength="370">${pct}%</text></g></svg>
          EOF

      - name: Commit badge
        if: github.event_name != 'pull_request'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add badges/coverage.svg
          git diff --cached --quiet && echo "No badge changes" || git commit -m "chore: update coverage badge to ${pct}%" || true
          git push
