name: lock-consistency

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 4 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  check-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install plugin (export) & deps (no dev needed)
        run: |
          poetry self add poetry-plugin-export || true
          poetry install --no-root --only main

      - name: Capture pre-lock hash
        id: before
        run: |
          echo "hash=$(sha256sum poetry.lock | cut -d' ' -f1)" >> "$GITHUB_OUTPUT"

      - name: Verify lock consistency
        run: |
          # '--check' exits non-zero if the lock would change; no file mutation.
          poetry lock --check || {
            echo "::error::Lock drift detected. Run 'poetry lock' locally and commit the updated poetry.lock." >&2
            exit 1
          }

      - name: Capture post-check hash
        id: compare
        run: |
          # File should be untouched when using '--check'. Hash purely for summary parity display.
          after_hash=$(sha256sum poetry.lock | cut -d' ' -f1)
          echo "after_hash=$after_hash" >> "$GITHUB_OUTPUT"
          echo "Lockfile stable (no drift)."

      - name: Summarize
        if: always()
        run: |
          cat >> "$GITHUB_STEP_SUMMARY" <<EOF
          ### Lock Consistency Report

          Original hash: \
          	${{ steps.before.outputs.hash }}
          After hash: \
          	${{ steps.compare.outputs.after_hash }}

          Result: $([ "${{ steps.before.outputs.hash }}" = "${{ steps.compare.outputs.after_hash }}" ] && echo "✅ Stable" || echo "❌ Drift Detected")
          EOF
