name: Unit and Integration Tests 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies (dev)
        env:
          POETRY_VIRTUALENVS_CREATE: "false"
        run: |
          poetry install --all-groups

      - name: Run tests
        env:
          TESTCONTAINERS_HOST_OVERRIDE: 127.0.0.1
        run: |
          poetry run pytest --config-file pyproject.toml -svv
